package com.tcargo.web.enumeraciones;

public enum TipoDeViaje {
//	LA ENUMERACION AMBOS HACE ALUSION A NACIONAL + INTERNACIONAL EN LA CREACION DE TIPOS DE REQUISITOS DE OFERTAS
    NACIONAL, INTERNACIONAL, IMPORTACION, EXPORTACION, AMBOS

}
